src: sample/demo.md
dst: sample/output/demo.xlsx
text:
  font:
    family: 游ゴシック Regular
    size: 11
code:
  font:
    family: Arial
    size: 10.5
max_num_of_characters_per_line: 120
heading_number: true
